### PR TITLE
Add first asteroid version

### PR DESCRIPTION
**Pull request by stefanofossati**
Add the first asteroid version

### CODE REVIEW

**Comment by spig95** [comment]
Are the files under the `UserSettings` folder needed? According to this conversation, it seems it can be removed from version control: https://forum.unity.com/threads/whats-the-usersettings-directory.754436/

(If so, in my opinion, you could rebase this branch on `develop`, remove the folder, and update the .gitignore directly in this PR)

**Comment by stefanofossati** [comment]
@spig95 ok prefect, I haven't noticed it. Thanks for the improvement

**Comment by stefanofossati** [comment]
The UserSetting is removed and the gitignore is updated

**Review by bottolo — APPROVED** [review]
Everything works as expected. 

As pointed out in a previous thread on Discord, further actions _may_ be needed such as a **spaceship count**  and a **mixer** in the settings.

**Pull request merged**
